### PR TITLE
fixes #137, does not leak symbols in rows in pg adapter

### LINKED ISSUE #137: `pg` adapter leaks symbols in rows
Hello again,
We noticed that rows being return from `pg` adapter queries include `Symbol(_id)`.
This is mostly aesthetic, but can be confusing. I'll be happy try a PR, do you have any pointers ?
Best,

```javascript
// pg-mem/src/tests/pg.spec.ts

it('does not leak symbol properties in rows', async () => {
    simpleDb();
    const { Client } = db.adapters.createPg();
    const client = new Client();
    await client.connect();

    many(`create table mytable (msg varchar);
        insert into mytable values ('hello'), ('hi');`);

    const got = await client.query('select * from mytable;');

    // fails
    expect(Object.getOwnPropertySymbols(got.rows[0]).length).to.be.equal(0);

    await client.end();
});
```

### PR DESCRIPTION
**Pull request by gabssnake**
Thanks for the pointers, hope this is fine.
Best,

### CODE REVIEW

File: src/adapters.ts [hunk 1]
```diff
@@ -128,16 +128,23 @@ export class Adapters implements LibAdapters {
...
                 return {
-                    ...rows,
+                    ...res,
+                    // clone rows to avoid leaking symbols
+                    rows: res.rows.map(row => {
+                        return Object.entries(row).reduce((obj, [key, val]) => {
+                            obj[key] = val;
+                            return obj;
+                        }, {});
+                    }),
```
Comment (oguimbal) [inline src/adapters.ts:143]: Any reason not to use `res.rows.map(row => Object.fromEntries(Object.entries(row))` ?

Comment (oguimbal) [reply src/adapters.ts:143]: Nevermind, you answered that in your PR comment !

**Comment by oguimbal** [comment]
Thanks !
